### ISSUE TITLE
Input selector [no issue, questions]

### ISSUE THREAD

**Issue by zigotica** [FutureSharks/preamp-two#21]
Hi Max,

I was about to buy the BOM for the input selector, too long inside a box in the closet. 

1. What is the expected voltage rating for C1_SMD?
2. Whatever value for RLED1 is fine?
3. Whatever color or specs for LED1 is fine?
4. Can I simply fill in 3 channels instead of 6?
5. What is the expected power supply and do the 2 power inputs need to be isolated?

Thank you so much

**Comment by FutureSharks** [comment]
Hi @zigotica 👋

1. It just needs to be higher than the power supply voltage, so higher than 5V. So 10V is a good value.
2. I used 1K so the LED isn't too bright
3. Whatever you want!
4. Yep! Might be better to update the code though, otherwise you will be waiting for it to cycle through the unused inputs
5. 5 volt

I hope that helps 🙂

**Comment by zigotica** [comment]
Thank you so much for the answers!

My real problem now is [MCP23S17-E/SO](https://www.mouser.es/ProductDetail/579-MCP23S17-E-SO) and all its family are unavailable at Mouser and Digikey... You don't know of an alternative SPI expander from another manufacturer, do you? May'23 seems a bit too long for just one piece. 

Thank you

**Comment by FutureSharks** [comment]
I don't think you can use another part in the PCB in place of the `MCP23S17-E/SO`. I'm sure you can find one on eBay or Aliexpress though 🙂

**Comment by zigotica** [comment]
Ah yes, didn't think about those. Already bought at Ali. Thank you!
